Repository yungyuc/sciwork20, pull requests merged in 2019-12, with the labels that each got.

#22 Add blog entry 'better-code'
  content/articles/1912-better-code.md
Labels: enhancement

#29 README: describe the current repository convention
  README.rst
Labels: enhancement

#26 Add information for tutorials
  content/pages/program.rst
  content/pages/tutorial/hypothesis-testing.rst
  content/pages/tutorial/packaging.rst
Labels: program

#27 Add prospectus
  content/pages/prospectus.md
  content/pages/prospectus.rst
  content/pages/sponsors.md
  content/pages/sponsors.rst
Labels: enhancement

#36 Submit some minor adjustments
  content/pages/tutorial/hypothesis-testing.rst
Labels: program

#38 Announce tutorial
  content/articles/1912-announce-tutorial.md
  mytheme/static/css/main.css
Labels: program

#45 Fix wrong year
  content/pages/venue.rst
Labels: bug

#46 Announce sprints
  content/articles/1912-announce-sprint.md
Labels: blog

#50 Tutorial packaging rev
  content/pages/tutorial/packaging.rst
Labels: program

#43 Add about page and include a list of staff
  content/pages/about.rst
  pelicanconf.py
Labels: enhancement

#52 Publish 12/28
  content/pages/about.rst
Labels: publish

#54 Add floor plan to the venue page
  content/images/sciwork_floorplan.svg
  content/pages/program.rst
  content/pages/venue.rst
  mytheme/static/css/main.css
  pelicanconf.py
Labels: enhancement
